- charts/crowdsec/Chart.yaml
- charts/crowdsec/templates/_helpers.tpl
This PR fixes #10. Basically it updates the existing secret with either the value from the `secrets.username` and `secrets.password` variable if they are set. If not it checks if the existing secret has some values and will reuse them. Only if the secret is not existing it will generate a new username and password.
> Prevent secret regeneration with helm update

- charts/crowdsec/Chart.yaml
- charts/crowdsec/README.md
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/templates/lapi-persistentVolume.yaml
- charts/crowdsec/values.yaml
This adds a persistent volume to the crowdsec helm chart so the database can be persistent and will survive a pod update. Currently if you destroy the lapi pod, the list of known bouncers is destroyed and you need to register them again.
> add persistent volume to crowdsec chart

- charts/crowdsec/Chart.yaml
- charts/crowdsec/README.md
- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/agent-service.yaml
- charts/crowdsec/templates/agent-serviceMonitor.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/templates/lapi-service.yaml
- charts/crowdsec/templates/lapi-serviceMonitor.yaml
- charts/crowdsec/values.yaml
This PR adds the possibility to enable or disable the metrics. If enabled there is also the possibility to deploy prometheus service monitors so prometheus can monitor the services. (Of course this only works if prometheus is configured to search in all namespaces for `ServiceMonitors`
> add service monitor for prometheus

- charts/crowdsec/Chart.yaml
- charts/crowdsec/templates/acquis-configmap.yaml
- charts/crowdsec/values.yaml
It will allow user to specify if crowdsec need to process json logs (when container runtime is Docker) or cri log format (when it's containerd)
> handle json or CRI output logs

- charts/crowdsec/Chart.yaml
- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/values.yaml
Hi, there can be some problems with domain name resolution on busybox's uclibc version. It it could be nice to make wait-for-lapi image customizable.
> make wait-for-lapi image customizable

- charts/crowdsec/templates/metabase-ingress.yaml
When setting multiple annotations the following error is returned :
```
Error: YAML parse error on crowdsec/templates/metabase-ingress.yaml: error converting YAML to JSON: yaml: line 5: did not find expected key
```
With the command `helm template crowdsec crowdsec/crowdsec -f crowdsec-values.yaml --debug` the following manifest is returned for the Ingress :
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
annotations:
nginx.ingress.kubernetes.io/backend-protocol: HTTP
traefik.ingress.kubernetes.io/router.entrypoints: websecure
traefik.ingress.kubernetes.io/router.tls: "true"
name: default-dashboard
labels:
k8s-app: crowdsec
type: lapi-dashboard
version: v1
spec:
[...]
```
This PR fixes this issue by setting `nindent 4` instead of `indent 1`
> Fix indentation for Ingress

- charts/crowdsec/README.md
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
LAPI deployment strategy needs to be configurable, for example when using PVC with accessMode ReadWriteOnce deployment cannot be updated with default RollingUpdate strategy
> make lapi deployment strategy configurable

- charts/crowdsec/templates/agent-daemonSet.yaml
Arguably the toleration should be up to the end user. And if the end user doesn't want to tolerate the master, so be it. No need for default values. 
This change removes the second tolerations definition, and moves it up to the top above the initContainer definition.
Closes #23
> move toleration definition

- charts/crowdsec/templates/acquis-configmap.yaml
Closes https://github.com/crowdsecurity/helm-charts/issues/48
I have no easy way to test this, but if there are steps I should take, let me know and I shall do my best.
I *have* tested the format by modifying the configmap directly with multiple `---` delimited entries, with success.
> fix(configmap): add delimiter to range

- charts/crowdsec/Chart.yaml
- charts/crowdsec/templates/agent-service.yaml
- charts/crowdsec/templates/lapi-service.yaml
- charts/crowdsec/values.yaml
This PR adds an option in the chart `crowdsec` to define the [externalTrafficPolicy](https://kubernetes.io/docs/concepts/services-networking/service/#external-traffic-policy) for agent and lapi services.
This setting is useful for preserving source IP when using services of type `LoadBalancer` and `NodePort`.
> Add externalTrafficPolicy setting to services

- charts/crowdsec/Chart.yaml
- charts/crowdsec/README.md
- charts/crowdsec/templates/NOTES.txt
- charts/crowdsec/templates/lapi-ingress.yaml
- charts/crowdsec/values.yaml
Perhaps this works for #57 . This Adds an optional ingress for lapi traffic. This is a way a non-kubernetes agent and/or bouncer can communicate with the lapi api. Its mostly copy/pasta. I've tested this and it works in my environment. I have two ingress-controllers, one is internal and the other external.
crowdsec agent monitoring external ingress-nginx logs.
crowdsec lapi exposed on internal ingress-nginx
opnsense running crowdsec agent and bouncer registered with crowdsec lapi
I look forward to any feedback.
> Add an optional ingress for lapi

- charts/crowdsec/templates/agent-configmap.yaml
- charts/crowdsec/templates/lapi-configmap.yaml
I tried to create multiple local parsers using the Crowdsec Helm chart by adding multiple entries to the `config.parsers.s01-parse` value:
```yaml
agent:
acquisition:
- namespace: test
podName: test-*
program: test
config:
parsers:
s01-parse:
parser1.yaml: |
name: local-parser-1
description: my local parser 1
parser2.yaml: |
name: local-parser-2
description: my local parser 2
parser3.yaml: |
name: local-parser-3
description: my local parser 3
```
However the configmap generated has a wrong indentation (lines 9 and 12 should be indented of 2, but it is 6). As result, the configmap has only one key and not three keys as expected (`parser1.yaml`, `parser2.yaml` and `parser3.yaml`)
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: crowdsec-parsers-s01-parse
data:
parser1.yaml: |
name: …
```
> fix wrong indentation of agent and lapi configmaps

- charts/crowdsec/Chart.yaml
- charts/crowdsec/README.md
- charts/crowdsec/templates/acquis-configmap.yaml
- charts/crowdsec/templates/agent-daemonSet.yaml
- use crowdsec 1.4.4-rc1 by default
- disable capi in agents (avoid wasteful register)
- enable force_inotify (also fixes the tls tutorial)
> release 0.8.1

- charts/crowdsec/Chart.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
When disabling persistent volumes for both lapi and agents, and enabling tls, crowdsec isn't working well because of volumes and volumeMounts.
+ Disable persistent volume for agents by default, so we'll avoid accessMode issues when they are multiple agents.
> crowdsec: fix tls bug when persistency is disabled

- charts/crowdsec/ci/crowdsec-values.yaml
- charts/crowdsec/templates/acquis-configmap.yaml
- charts/crowdsec/values.schema.json
- charts/crowdsec/values.yaml
This adds the notion of a `manualAcquisition` in order to facilitate manual specification of acquisitions outside of containers specifically.
`/var/log` is already a mapped volume, so theoretically you can specify a manual acquis for any other log file of your desire, such as `auth.log` rather than only being able to parse container logs.
This is an attempt to solve for #88 -- though I made assumptions on naming conventions and such and am completely open to altering it, if the idea in general is accepted.
Here is an example:
Using manual acquis + some dummy normal acquis:
```yaml
additionalAcquisition:
- filenames:
- /var/log/auth.log
labels:
type: syslog
program: sshd
acquisition:
- namespace: "foo" #ingress-nginx
podName: "foo-*" #ingress-nginx-controller-*
program: "foo" #nginx
``` …
> feat(acquisition): add manual acquisition

- charts/crowdsec/Chart.yaml
- charts/crowdsec/templates/agent-serviceMonitor.yaml
- charts/crowdsec/templates/lapi-serviceMonitor.yaml
A small tweak to servicemonitor to add `machine` label based on node name
Added because by default the v4 Grafana dashboards rely on it
> add `machine` label to servicemonitors

- charts/crowdsec/templates/agent-daemonSet.yaml
The agent DaemonSet needs to mount `/var/log` to parse node logs. However, on GKE Autopilot clusters, `hostPath` mounts are required to be in `readOnly` mode, making the `crowdsec` chart unusable on the platform: 
```
admission webhook "warden-validating.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints. 
Violations details: {"[denied by autogke-no-write-mode-hostpath]":["hostPath volume varlog in container crowdsec-agent is accessed in write mode; disallowed in Autopilot."]}
```
Mounting `/var/log` as readOnly would fix the issue and doesn't seem to affect how Crowdsec works.
> Mount /var/log as readOnly

- charts/crowdsec/README.md
- charts/crowdsec/templates/acquis-configmap.yaml
- charts/crowdsec/values.schema.json
- charts/crowdsec/values.yaml
Adds the option poll_without_inotify to pod and file acquisitions to match the currently documented option at https://docs.crowdsec.net/docs/data_sources/file
> Add option for poll_without_inotify

- charts/crowdsec/templates/tls/ca-issuer.yaml
Missing templating name in Issuer
This failed if release name is not "crowdsec"
> Template name ca issuer

- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
Alpine linux image does not handle well DNS resolution when used with Rancher Kubernetes type distribution.
You need to add this in Deployment to be able to resolve hostnames:
```yaml
dnsConfig:
options:
- name: ndots
value: '1'
```
> dnsConfig support for alpine linux

- charts/crowdsec-traefik-bouncer/templates/deployment.yaml
- charts/crowdsec-traefik-bouncer/values.yaml
- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
Adds the option to set an existing `priorityClassName`. This means we would be able to ensure Crowdsec gets scheduled on a particular set of nodes we have.
> Adding priorityClassName

- .github/governance.yaml
- .github/workflows/governance-bot.yaml
In this PR the governance bot is setup to:
* autoassign one among '@he2ss', '@blotus', '@buixor', '@mmetc', '@LaurenceJJones'
* request kind to be set on issues and kind+area on pr
* Tag issue as 'stale' avec 30d of tag ''provide more details'
* Close issue staged 'stale' after 60d without activity
> adding v0.1 of governance bot

- .github/workflows/governance-bot.yaml
I forgot to uncomment the github token param, so this Pr fixes it
> uncomment github-token param for gov bot config

- charts/crowdsec/Chart.yaml
- charts/crowdsec/README.md
- charts/crowdsec/templates/_helpers.tpl
- charts/crowdsec/templates/lapi-configmap.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/templates/lapi-secrets.yaml
- charts/crowdsec/values.schema.json
- charts/crowdsec/values.yaml
- Add "lapi.replicas" in values and deployment templates
- Add "lapi.affinity" in values.yaml, as it was missing, and thus not included in the the documentation
- Add "lapi.topologySpreadConstraints" in values and deployment template.
- Add a configuration override, to be able to configure and external DB (among other things, as described [here](https://docs.crowdsec.net/docs/configuration/crowdsec_configuration/#configuration-example)). It creates a "config.yaml.local" file in the crowdsec config directory, so default config values are kept.
- Add "lapi.secrets.csLapiSecret" in values, create a secret and define it as env vars for deployment. This is required because it must be identical for every lapi pods. It will be generated automatically if not specified by the user.
- Add …
> Support for LAPI High availability

- charts/crowdsec/templates/tls/agent-certificate.yaml
- charts/crowdsec/templates/tls/bouncer-certificate.yaml
- charts/crowdsec/templates/tls/ca-certificate.yaml
- charts/crowdsec/templates/tls/ca-issuer.yaml
- charts/crowdsec/templates/tls/crowdsec-clusterIssuer.yaml
- charts/crowdsec/templates/tls/lapi-certificate.yaml
- charts/crowdsec/values.yaml
Allows configuration of custom Issuer or ClusterIssuer when TLS is enabled using cert-manager.
Related issues: #93
> Add support for custom tls issuer

- charts/crowdsec/templates/tls/agent-certificate.yaml
- charts/crowdsec/templates/tls/bouncer-certificate.yaml
- charts/crowdsec/templates/tls/lapi-certificate.yaml
- charts/crowdsec/values.yaml
Add options to configure ```duration``` and ```renewBefore``` fields for Certificates resources.
Default values are set to cert-manager's default, ```duration = 90d```, and ```renewBefore = 30d```.
> Add duration and renewBefore values for cert-manager certificates

- charts/crowdsec-traefik-bouncer/templates/middleware.yaml
Old traefik crds are deprecated and with traefik v3 not used anymore, so upgrade middleware api to traefik.io/v1alpha1
> Middleware API Version traefik.io/v1alpha1

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/values.yaml
On a Kubernetes distribution like [Talos](https://www.talos.dev), a `hostPath` can cause issue with pod security.
Example of the agent DaemonSet :
```
Events:
Type     Reason            Age                    From                  Message
----     ------            ----                   ----                  -------
Warning  FailedCreate      57m                    daemonset-controller  Error creating: pods "crowdsec-agent-9x8ww" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "varlog", "varlibdockercontainers")
Warning  FailedCreate      41m                    daemonset-controller  Error creating: pods "crowdsec-agent-jv295" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "varlog", "varlibdockercontainers")
Warning …
```
> Add option to disable varlog hostPath

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/templates/tls/agent-certificate.yaml
- charts/crowdsec/templates/tls/bouncer-certificate.yaml
- charts/crowdsec/templates/tls/lapi-certificate.yaml
- charts/crowdsec/values.yaml
Add values to configure ```secretTemplate``` of ```certificate``` resources. Also add ```annotations``` to ```deployment``` and ```daemonset``` for lapi and agent.
This is required to add specific annotations for [Reloader](https://github.com/stakater/Reloader), which is a tool providing a workaround for #133, by triggering a rollout when it detects a secret change.
/kind enhancement
> Add annotations to LAPI deploy, Agent daemonset and secretTemplate for certificates

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
Add a checksum annotation of Configmaps and Secrets to pods, so it trigger a restart when one of them changes.
Also, there is an issue, when both ```podAnnotations``` and ```lapi.podAnnotations``` are both set, only ```podAnnotation``` is  used, and the other is ignored (because of a else if). Same issue for the agent.
This PR fixes it, by adding both when they both are defined.
> Add annotations to trigger restart when configmap or secret changes

- charts/crowdsec-traefik-bouncer/Chart.yaml
Mark traefik bouncer as deprecated by helm chart this will:
- Mark deprecation within helm chart
- Docs generation will add a note that chart is deprecated
- Anyone using the chart when updating will inform them this is now deprecated
> enhance: Mark traefik helm chart as deprecated

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
Fix issue introduced by myself in #179, which I fixed in local but forgot to push, sorry about that.
Setting ```podAnnotations``` or ```lapi.podAnnotations```  break the manifest because of a bad indentation and ```{{-```, so it produce something like this:
values.yaml
```
podAnnotations:
allPods: test
agent:
daemonsetAnnotations:
agentDs: test
podAnnotations:
agentPod: test
acquisition:
- namespace: ingress-nginx
podName: ingress-nginx-controller-*
program: nginx
lapi:
deployAnnotations:
lapiDeploy: test
podAnnotations:
lapiPod: test
```
result
```
[...]
spec:
template:
metadata:
annotations:
checksum/agent-secret: 33b575d4037387fc40a4e87bf644d8ef410d911d42cf9ac5c16c81f6f9208cd7
checksum/lapi-secret: 6a759b5ae3a48ec705b7af68a0947c9e286ccae6d02a73f922e32d0fe88bfc4c …
```
> [Fix] indentation for deploy, ds and pod annotations

- charts/crowdsec/templates/lapi-deployment.yaml
Fix dashboard init trying to ask for confirmation when overwriting existing db (don't overwrite)
Fixes crowdsecurity/helm-charts#86
> Fix dashboard init trying to ask for confirmation when overwriting existing db

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
Add values to add extraVolumes and extraVolumeMounts to lapi and agent pods.
I only need ```lapi.extraVolumes``` for an initContainer, but I figured it's easy to add these for both the agent and lapi, which could come handy for someone else.
Tested with the following values:
```
agent:
acquisition:
- namespace: ingress-nginx
podName: ingress-nginx-controller-*
program: nginx
extraVolumes:
- name: agent-vol
configMap:
name: custom-agent-cm
extraVolumeMounts:
- name: agent-vol
mountPath: /tmp/agent-vol
lapi:
persistentVolume:
data:
enabled: false
config:
enabled: false
extraVolumes:
- name: lapi-vol
configMap:
name: custom-lapi-cm
extraVolumeMounts:
- name: lapi-vol
mountPath: /tmp/lapi-vol
```
/kind enhancement
> Add values to add extraVolumes to lapi and agent

- charts/crowdsec/README.md
- charts/crowdsec/ci/crowdsec-values.yaml
- charts/crowdsec/templates/NOTES.txt
- charts/crowdsec/templates/appsec-configmap.yaml
- charts/crowdsec/templates/appsec-deployment.yaml
- charts/crowdsec/templates/appsec-service.yaml
- charts/crowdsec/templates/appsec-serviceMonitor.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/templates/lapi-secrets.yaml
- charts/crowdsec/templates/tests/test_appsec_up.yaml
- charts/crowdsec/values.yaml
fix #170 
Adding the ability to configure and enable the [Appsec Component](https://docs.crowdsec.net/docs/next/appsec/intro).
In the Kubernetes environment, to be able to handle inband and out of band, we deployed an extra pod with an agent responsible only to receive bouncers appsec traffic.
Depends on : https://github.com/crowdsecurity/crowdsec/pull/3202
:warning: Do not merge before new crowdsec release including this PR
> add appsec in crowdsec chart

- charts/crowdsec/templates/tls/agent-certificate.yaml
- charts/crowdsec/templates/tls/bouncer-certificate.yaml
When using a values file like the following ([taken from this crowdsec blog post](https://www.crowdsec.net/blog/integrating-crowdsec-kubernetes-tls)):
```
container_runtime: containerd
tls:
enabled: true
bouncer:
reflector:
namespaces: ["traefik"]
agent:
acquisition:
- namespace: traefik
podName: traefik-*
program: traefik
env:
- name: PARSERS
value: "crowdsecurity/cri-logs"
- name: COLLECTIONS
value: "crowdsecurity/traefik"
- name: DISABLE_PARSERS
value: "crowdsecurity/whitelists"
persistentVolume:
config:
enabled: false
lapi:
dashboard:
enabled: false
ingress:
host: my-crowdsec.lan
enabled: true
persistentVolume:
config:
enabled: false
env:
- name: DISABLE_ONLINE_API
value: "true"
```
The following error is observed:
```
Could not determine release state: unable to determine cluster …
```
> fix(crowdsec): Prevent empty annotation error for cert manifests

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/agent-deployment.yaml
When `tls.enabled` is false and `agent.persistence.config.enabled` is true, the container command is put twice in the yaml.
This fix consildates both command statements and fixes #224
> Bugfix: double command for agent container

- charts/crowdsec/templates/capi-credentials-secrets.yaml
Hello!
It seems that there is an issue with the new central API register job.
The job is created as a pre-install and a pre-upgrade helm hook, and requires the capi-credentials secret to exist.
But this secret is only created as a pre-install helm hook.
So for a new install it works perfectly, but if you upgrade an existing helm release then the register job will be stuck as it cannot find its secret.
This PR should solve the issue.
> fix(crowdsec): Create capi-credentials secrets in pre-upgrade

- charts/crowdsec/README.md.gotmpl
- charts/crowdsec/values.yaml
- Activated auto registration by default so the charts works with the default `values.yaml` (fix for #228)
- Added documentation on authentication, including auto registration, TLS client authentication and flushing old machines (fix for #230)
- Removed auto registration token from Appsec documentation (moved into authentication)
- Fixed a few typos
> Activate auto registration token by default and update docs on authentication

- cr.yaml
Enables release note generation via an option provided by chart-releaser. chart-releaser uses GitHub's feature for automatic release note generation (https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). 
This makes it easier to detect the changes a new release brings.
> Added generated release notes to release workflow

- charts/crowdsec/templates/capi-register-job.yaml
Hello !
I created this PR to add the ability to customize the labels of the capi-register pod.
In our project we use labels to redirect application logs to different ElasticSearch indexes.
/kind feature
> feat(capi-register-job): add custom labels to CAPI register pod

- charts/crowdsec/Chart.yaml
This CrowdSec version includes the option to set agents to self delete instead of waiting for flush timer
You can achieve this by configuring inside the values.yaml: **(note the example shown is an extension of the default values)**
```yaml
config:
config.yaml.local: |
api:
client:
unregister_on_exit: true ## false means either no delete or wait for flush timer
server:
auto_registration: # Activate if not using TLS for authentication
enabled: true
token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
allowed_ranges: # /!\ Make sure to adapt to the pod IP ranges used by your cluster
- "127.0.0.1/32"
- "192.168.0.0/16"
- "10.0.0.0/8"
- "172.16.0.0/12"
```
> bump v1.6.9, chart bump
