- .github/workflows/update_docs.yaml
- charts/crowdsec/Chart.yaml
- charts/crowdsec/README.md
- charts/crowdsec/values.yaml
- charts/helloworld/README.md
Charts documentation generated automatically from github action.
You just need to update Chart description + comment well the values.yaml files
> add doc for crowdsec chart

- charts/crowdsec/README.md
- charts/crowdsec/templates/metabase-ingress.yaml
- charts/crowdsec/values.yaml
This PR adds ingress support. I did not change the chart version number as there is also another PR and I don't want to mix the numbers
Let me know if something is missing
> Add ingress support to helm chart

- charts/crowdsec/README.md
- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/agent-persistentVolume.yaml
- charts/crowdsec/values.yaml
> Add PVC for crowdsec agent

- charts/crowdsec/README.md
> update readme for pr 29

- .github/workflows/lint-test.yaml
- charts/crowdsec/Chart.yaml
- charts/crowdsec/ci/crowdsec-values.yaml
- charts/crowdsec/templates/tests/test_agent_up.yaml
- charts/crowdsec/templates/tests/test_lapi_up.yaml
- charts/crowdsec/values.yaml
* add github action to lint and test crowdsec chart
* add fixed appVersion in chart
> crowdsec : add github action to lint and test 

- charts/crowdsec-traefik-bouncer/Chart.yaml
- charts/crowdsec-traefik-bouncer/README.md
- charts/crowdsec-traefik-bouncer/templates/deployment.yaml
- charts/crowdsec-traefik-bouncer/values.yaml
A new parameter in value.yaml has been added, allowing user to specify the value for the env variable GIN_MODE, which allows user to set it to release when in production
> Added config parameter to set GIN_MODE to production

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/agent-persistentVolume.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/templates/lapi-persistentVolume.yaml
- charts/crowdsec/values.yaml
Hi,
This PR adds several best-practive security options to all resources, defines probes and sets resources. It also fixes https://github.com/crowdsecurity/helm-charts/issues/85 by updating the if statement.
> Update security, probes, resources and PVCs

- charts/crowdsec/Chart.yaml
> crowdsec: update crowdsec bin version

- charts/crowdsec/Chart.yaml
Latest binary is at v1.5.2 and this is a proposed tweak to move to v1.5.2
> Update Chart to latest binary v1.5.2

- charts/crowdsec/Chart.yaml
containing those changes : 
https://github.com/crowdsecurity/helm-charts/pull/107
https://github.com/crowdsecurity/helm-charts/pull/108
https://github.com/crowdsecurity/helm-charts/pull/109
> bump chart version

- charts/crowdsec/Chart.yaml
> bump version 1.6.0

- charts/crowdsec/values.yaml
Instead of empty object
Fixes #134
> Switch tolerations to empty map in bundled values.yaml

- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
> add env vars on the dashboard image to config metabase

- charts/crowdsec-traefik-bouncer/Chart.yaml
- charts/crowdsec-traefik-bouncer/templates/deployment.yaml
- charts/crowdsec-traefik-bouncer/values.yaml
+ update image and bump version
fix https://github.com/crowdsecurity/helm-charts/issues/63 and https://github.com/crowdsecurity/helm-charts/issues/106
> add env vars to traefik bouncer 

- charts/crowdsec/templates/lapi-deployment.yaml
Fixes crowdsecurity/helm-charts#55
> Fix dashboard data volumes to use PVC instead of emptyDir

- charts/crowdsec/values.yaml
> update restart strategy to Recreate

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
Hello again 👋 
This PR adds the possibility to have imagePullSecrets defined for crowdsec deployment & daemonset.
This has been tested but feel free to suggest any changes if that change does not satisfy your coding habits!
> Add imagePullSecrets for crowdsec chart

- .github/workflows/governance-bot.yaml
oups... my bad for wanting to unify extensions :D
> fix typo in config name for gov bot

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
Hello there! 👋 
This PR adds the possibility to have labels & annotations added to the pods with the crowdsec helm chart.
This has been tested but feel free to suggest any changes if that change does not satisfy your coding habits!
> Add podLabels & podAnnotations for crowdsec chart

- charts/crowdsec/values.yaml
* fix chart doc following this https://github.com/crowdsecurity/helm-charts/pull/148
* adding forgotten params `affinity` in agent and lapi
> fix doc + add forgotten values param

- .github/workflows/governance-bot.yaml
change schedule frequency to once a day at 23:00
right now every hour is useless and very spammy
> Reduce governance schedule frequency

- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
Hello there! 👋 
Again, pretty self-explanatory
Do not hesitate if you have any questions or suggestions
> Add lifecycle support for LAPI

- charts/crowdsec/Chart.yaml
But firstly, the issue https://github.com/crowdsecurity/crowdsec/issues/2944 must be resolved
> Update to v1.6.1

- charts/crowdsec/values.yaml
> set higher resources limits

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/values.yaml
Small improvement, to be able to configure custom InitContainers for both LAPI and Agent pods.
> Add values to add extra InitContainers to agent and lapi

- charts/crowdsec/templates/agent-serviceMonitor.yaml
- charts/crowdsec/templates/lapi-serviceMonitor.yaml
- charts/crowdsec/values.yaml
> add additionalLabels for service monitors

- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/agent-deployment.yaml
caused helm to crash with tls enabled
> fix template quote

- charts/crowdsec/values.schema.json
Related PR: https://github.com/crowdsecurity/crowdsec/pull/3310
> charts/crowdsec/values.schema: add rules for VictoriaLogs

- charts/crowdsec/templates/_helpers.tpl
- charts/crowdsec/templates/agent-daemonSet.yaml
- charts/crowdsec/templates/agent-deployment.yaml
- charts/crowdsec/templates/appsec-deployment.yaml
- charts/crowdsec/templates/lapi-deployment.yaml
- charts/crowdsec/templates/lapi-secrets.yaml
- charts/crowdsec/values.yaml
Fixes: #257 
/kind enhancement
> Support external secret

- charts/crowdsec/templates/agent-podMonitor.yaml
- charts/crowdsec/templates/appsec-podMonitor.yaml
- charts/crowdsec/templates/lapi-podMonitor.yaml
- charts/crowdsec/values.yaml
> Add support for PodMonitors and scraping metrics from PODs

- charts/crowdsec/templates/appsec-deployment.yaml
> Fix podAnnotations in appsec deployment

- charts/crowdsec/templates/_helpers.tpl
> Fix registration token being regenerated on redeploy
